import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ThemeConfigProvider from "@/shared/providers/theme-config-provider";
import { ThemeModeProvider } from "@/shared/providers/theme-mode-provider";
import { cookies } from "next/headers";
import { THEME_KEY } from "@/constants/app-config";

import "@ant-design/v5-patch-for-react-19";
import "@/styles/styles.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Warehouse",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieTheme = (await cookies()).get(THEME_KEY)?.value;
  const isDark = cookieTheme === "dark";

  return (
    <html lang="en" data-theme={isDark ? "dark" : "light"}>
      <body className={`${poppins.variable} antialiased`}>
        <AntdRegistry>
          <ThemeModeProvider>
            <ThemeConfigProvider>{children}</ThemeConfigProvider>
          </ThemeModeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
